### ISSUE TITLE
`pip install .` fails

### ISSUE THREAD

**Issue by jakob1379** [tristanpenman/lung-segmentation-tool#1]
Hello there. I wish to test out your tool, which seems promising, but I an error when trying to install the program after installing the requirements

```
pip install .
Processing /home/fuzie/Documents/Speciale/code/lung_segment_test/lung-segmentation-tool
    ERROR: Command errored out with exit status 1:
     command: /home/fuzie/.pyenv/versions/3.8.0/envs/lung-test/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-gqbyrv6y/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-gqbyrv6y/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-fffs_g8k
         cwd: /tmp/pip-req-build-gqbyrv6y/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-gqbyrv6y/setup.py", line 18, in <module>
        setup(name='Lung Segmentation Tool',
      File "/home/fuzie/.pyenv/versions/3.8.0/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/fuzie/.pyenv/versions/3.8.0/envs/lung-test/lib/python3.8/site-packages/setuptools/dist.py", line 445, in __init__
        _Distribution.__init__(self, {
      File "/home/fuzie/.pyenv/versions/3.8.0/lib/python3.8/distutils/dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/home/fuzie/.pyenv/versions/3.8.0/lib/python3.8/distutils/dist.py", line 1227, in set_requires
        distutils.versionpredicate.VersionPredicate(v)
      File "/home/fuzie/.pyenv/versions/3.8.0/lib/python3.8/distutils/versionpredicate.py", line 114, in __init__
        raise ValueError("expected parenthesized list: %r" % paren)
    ValueError: expected parenthesized list: '-python'
    ----------------------------------------
WARNING: Discarding file:///home/fuzie/Documents/Speciale/code/lung_segment_test/lung-segmentation-tool. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It seems like there is an error in the install file.

I run manjaro and have python 3.8.0

**Comment by tristanpenman** [comment]
Apologies for the slow reply on this one. I don't think I ever received a notification for this issue, and only just discovered it by accident.

This should be fixed in commit 7a18bcb. Feel free to re-open the issue if this does not resolve it for you.
